package com.autonavi.gbl.pos.model;

import com.autonavi.gbl.common.model.Coord3DInt32;
import com.autonavi.gbl.pos.model.LocDataType;
import com.autonavi.gbl.pos.model.LocGNSSStatus;
import com.autonavi.gbl.pos.model.LocMoveStatus;
import java.io.Serializable;
import java.math.BigInteger;
/* loaded from: classes2.dex */
public class LocInnerGADSignal implements Serializable {
    public float accQ;
    public float airAlt;
    public float angleSpeed;
    public float azi;
    public float aziAcc;
    public float aziConfidence;
    public float aziDeviation;
    public float aziGps;
    public boolean bMountAngleReady;
    public short checkStatus;
    public float compassAzi;
    public float confidence;
    @LocDataType.LocDataType1
    public int dataType;
    public double deltaBearing;
    public double deltaPos;
    public float dq;
    public float dqAzi;
    public float dqPos;
    public short driveMode;
    public Coord3DInt32 ectRawPos;
    public float errorDist;
    public float fusionedHeading;
    public float fusionedHeadingAcc;
    public float gpsAlt;
    @LocGNSSStatus.LocGNSSStatus1
    public int gpsStatus;
    public BigInteger gpsTime;
    public boolean mayBadAzi;
    public byte mode;
    public byte mounted;
    public double moveDist;
    @LocMoveStatus.LocMoveStatus1
    public int moveStatus;
    public float noMoveAvgSpd;
    public long noMoveCount;
    public int num;
    public long overhead;
    public float pitch;
    public Coord3DInt32 pos;
    public float posAcc;
    public Coord3DInt32 posGps;
    public float rawAccuracy;
    public float rawAzi;
    public Coord3DInt32 rawPos;
    public float rawSpd;
    public long sceneState;
    public float slopeAcc;
    public float slopeValue;
    public float smoothAzi;
    public Coord3DInt32 smoothPos;
    public float smoothSpd;
    public int sourType;
    public float spd;
    public float spdGps;
    public BigInteger tickTime;
    public int timeDiff;
    public short uHwFlag;
    public BigInteger uLinkId;
    public short uSnrConfidence;
    public short uSnrOverheadState;
    public boolean unbelive;
    public float unionConfidence;

    public LocInnerGADSignal() {
        this.dataType = 0;
        this.gpsTime = new BigInteger("0");
        this.tickTime = new BigInteger("0");
        this.sourType = 0;
        this.pos = new Coord3DInt32();
        this.rawPos = new Coord3DInt32();
        this.ectRawPos = new Coord3DInt32();
        this.azi = 0.0f;
        this.spd = 0.0f;
        this.compassAzi = 0.0f;
        this.gpsAlt = 0.0f;
        this.airAlt = 0.0f;
        this.overhead = 0L;
        this.gpsStatus = 86;
        this.posAcc = 0.0f;
        this.rawAccuracy = 0.0f;
        this.rawAzi = 0.0f;
        this.rawSpd = 0.0f;
        this.checkStatus = (short) 0;
        this.timeDiff = 0;
        this.dq = 0.0f;
        this.confidence = 0.0f;
        this.aziConfidence = 0.0f;
        this.aziDeviation = 0.0f;
        this.unionConfidence = 0.0f;
        this.accQ = 0.0f;
        this.noMoveCount = 0L;
        this.noMoveAvgSpd = 0.0f;
        this.dqPos = 0.0f;
        this.dqAzi = 0.0f;
        this.unbelive = false;
        this.smoothSpd = 0.0f;
        this.smoothPos = new Coord3DInt32();
        this.smoothAzi = 0.0f;
        this.mayBadAzi = false;
        this.angleSpeed = 0.0f;
        this.fusionedHeading = 0.0f;
        this.fusionedHeadingAcc = 0.0f;
        this.driveMode = (short) 0;
        this.deltaBearing = 0.0d;
        this.deltaPos = 0.0d;
        this.mode = (byte) 0;
        this.num = 0;
        this.aziAcc = 0.0f;
        this.moveStatus = 0;
        this.sceneState = 0L;
        this.slopeValue = 0.0f;
        this.slopeAcc = 0.0f;
        this.moveDist = 0.0d;
        this.bMountAngleReady = false;
        this.pitch = 0.0f;
        this.mounted = (byte) 0;
        this.errorDist = 0.0f;
        this.posGps = new Coord3DInt32();
        this.aziGps = 0.0f;
        this.spdGps = 0.0f;
        this.uSnrOverheadState = (short) 0;
        this.uSnrConfidence = (short) 0;
        this.uHwFlag = (short) 0;
        this.uLinkId = new BigInteger("0");
    }

    public LocInnerGADSignal(@LocDataType.LocDataType1 int i, BigInteger bigInteger, BigInteger bigInteger2, int i2, Coord3DInt32 coord3DInt32, Coord3DInt32 coord3DInt322, Coord3DInt32 coord3DInt323, float f, float f2, float f3, float f4, float f5, long j, @LocGNSSStatus.LocGNSSStatus1 int i3, float f6, float f7, float f8, float f9, short s, int i4, float f10, float f11, float f12, float f13, float f14, float f15, long j2, float f16, float f17, float f18, boolean z, float f19, Coord3DInt32 coord3DInt324, float f20, boolean z2, float f21, float f22, float f23, short s2, double d, double d2, byte b, int i5, float f24, @LocMoveStatus.LocMoveStatus1 int i6, long j3, float f25, float f26, double d3, boolean z3, float f27, byte b2, float f28, Coord3DInt32 coord3DInt325, float f29, float f30, short s3, short s4, short s5, BigInteger bigInteger3) {
        this.dataType = i;
        this.gpsTime = bigInteger;
        this.tickTime = bigInteger2;
        this.sourType = i2;
        this.pos = coord3DInt32;
        this.rawPos = coord3DInt322;
        this.ectRawPos = coord3DInt323;
        this.azi = f;
        this.spd = f2;
        this.compassAzi = f3;
        this.gpsAlt = f4;
        this.airAlt = f5;
        this.overhead = j;
        this.gpsStatus = i3;
        this.posAcc = f6;
        this.rawAccuracy = f7;
        this.rawAzi = f8;
        this.rawSpd = f9;
        this.checkStatus = s;
        this.timeDiff = i4;
        this.dq = f10;
        this.confidence = f11;
        this.aziConfidence = f12;
        this.aziDeviation = f13;
        this.unionConfidence = f14;
        this.accQ = f15;
        this.noMoveCount = j2;
        this.noMoveAvgSpd = f16;
        this.dqPos = f17;
        this.dqAzi = f18;
        this.unbelive = z;
        this.smoothSpd = f19;
        this.smoothPos = coord3DInt324;
        this.smoothAzi = f20;
        this.mayBadAzi = z2;
        this.angleSpeed = f21;
        this.fusionedHeading = f22;
        this.fusionedHeadingAcc = f23;
        this.driveMode = s2;
        this.deltaBearing = d;
        this.deltaPos = d2;
        this.mode = b;
        this.num = i5;
        this.aziAcc = f24;
        this.moveStatus = i6;
        this.sceneState = j3;
        this.slopeValue = f25;
        this.slopeAcc = f26;
        this.moveDist = d3;
        this.bMountAngleReady = z3;
        this.pitch = f27;
        this.mounted = b2;
        this.errorDist = f28;
        this.posGps = coord3DInt325;
        this.aziGps = f29;
        this.spdGps = f30;
        this.uSnrOverheadState = s3;
        this.uSnrConfidence = s4;
        this.uHwFlag = s5;
        this.uLinkId = bigInteger3;
    }
}
