package com.autonavi.gbl.pos.model;

import com.autonavi.gbl.common.model.Coord3DDouble;
import com.autonavi.gbl.pos.model.LocStartDirType;
import com.autonavi.gbl.pos.model.LocStartPosType;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
/* loaded from: classes2.dex */
public class LocInfo implements Serializable {
    public float alt;
    public float altAcc;
    public boolean bSnrVoiceBroadcastState;
    public short bindFlag;
    public long buildingId;
    public float compassDir;
    public float courseAcc;
    public float distFromHeadLine;
    public float errorDist;
    public float fittingCourse;
    public float fittingCourseAcc;
    public short[] floor;
    public float gpsCoureAcc;
    public float gpsCourse;
    public GPSDatetime gpsDatetime;
    public float gpsDir;
    public Coord3DDouble gpsPos;
    public float hdop;
    public BigInteger inputTickTime;
    public boolean isAoi;
    public int isHLocData;
    public boolean isInParking;
    public boolean isLinkOnline;
    public int isSimulate;
    public int isUse;
    public long linkId;
    public int linkOnlineVersion;
    public boolean locInfoChange;
    public ArrayList<LocMatchInfo> matchInfo;
    public long matchInfoCnt;
    public float matchRoadCourse;
    public int naviRouteId;
    public long nearRoadId;
    public long overhead;
    public byte parkingFloorNo;
    public byte parkingLinkType;
    public short[] poiId;
    public float posAcc;
    public String requestRouteInfo;
    public int roadDir;
    public long roadId;
    public ArrayList<LocRoadMatchInfo> roadMatchInfo;
    public long roadMatchInfoCnt;
    public int segIdx;
    public float showPosAcc;
    public int sourType;
    public float speed;
    public float speedometer;
    public boolean speedometerIsValid;
    public Coord3DDouble stDoorInPos;
    public Coord3DDouble stMatchRoadPos;
    @LocStartDirType.LocStartDirType1
    public int startDirType;
    @LocStartPosType.LocStartPosType1
    public int startPosType;
    public BigInteger tickTime;

    public LocInfo() {
        this.isUse = 0;
        this.isSimulate = 0;
        this.sourType = 0;
        this.alt = 0.0f;
        this.speed = 0.0f;
        this.posAcc = 0.0f;
        this.showPosAcc = 0.0f;
        this.altAcc = 0.0f;
        this.gpsPos = new Coord3DDouble();
        this.gpsCourse = 0.0f;
        this.naviRouteId = 0;
        this.roadDir = 0;
        this.roadId = 0L;
        this.nearRoadId = 0L;
        this.segIdx = 0;
        this.bindFlag = (short) 0;
        this.distFromHeadLine = 0.0f;
        this.isHLocData = 0;
        this.linkId = 0L;
        this.isLinkOnline = false;
        this.linkOnlineVersion = 0;
        this.stDoorInPos = new Coord3DDouble();
        this.stMatchRoadPos = new Coord3DDouble();
        this.startDirType = 1;
        this.matchRoadCourse = 0.0f;
        this.requestRouteInfo = "";
        this.compassDir = 0.0f;
        this.gpsDir = 0.0f;
        this.errorDist = 0.0f;
        this.startPosType = 1;
        this.courseAcc = 0.0f;
        this.gpsCoureAcc = 0.0f;
        this.fittingCourse = 0.0f;
        this.fittingCourseAcc = 0.0f;
        this.gpsDatetime = new GPSDatetime();
        this.tickTime = new BigInteger("0");
        this.inputTickTime = new BigInteger("0");
        this.overhead = 0L;
        this.matchInfo = new ArrayList<>();
        this.matchInfoCnt = 0L;
        this.hdop = -1.0f;
        this.roadMatchInfo = new ArrayList<>();
        this.roadMatchInfoCnt = 0L;
        this.locInfoChange = false;
        this.bSnrVoiceBroadcastState = false;
        this.isAoi = false;
        this.speedometerIsValid = false;
        this.speedometer = 0.0f;
        this.isInParking = false;
        this.parkingFloorNo = (byte) 0;
        this.parkingLinkType = (byte) -1;
        this.buildingId = 0L;
        this.poiId = new short[32];
        this.floor = new short[32];
    }

    public LocInfo(int i, int i2, int i3, float f, float f2, float f3, float f4, float f5, Coord3DDouble coord3DDouble, float f6, int i4, int i5, long j, long j2, int i6, short s, float f7, int i7, long j3, boolean z, int i8, short[] sArr, short[] sArr2, Coord3DDouble coord3DDouble2, Coord3DDouble coord3DDouble3, @LocStartDirType.LocStartDirType1 int i9, float f8, String str, float f9, float f10, float f11, @LocStartPosType.LocStartPosType1 int i10, float f12, float f13, float f14, float f15, GPSDatetime gPSDatetime, BigInteger bigInteger, BigInteger bigInteger2, long j4, ArrayList<LocMatchInfo> arrayList, long j5, float f16, ArrayList<LocRoadMatchInfo> arrayList2, long j6, boolean z2, boolean z3, boolean z4, boolean z5, float f17, boolean z6, byte b, byte b2, long j7) {
        this.isUse = i;
        this.isSimulate = i2;
        this.sourType = i3;
        this.alt = f;
        this.speed = f2;
        this.posAcc = f3;
        this.showPosAcc = f4;
        this.altAcc = f5;
        this.gpsPos = coord3DDouble;
        this.gpsCourse = f6;
        this.naviRouteId = i4;
        this.roadDir = i5;
        this.roadId = j;
        this.nearRoadId = j2;
        this.segIdx = i6;
        this.bindFlag = s;
        this.distFromHeadLine = f7;
        this.isHLocData = i7;
        this.linkId = j3;
        this.isLinkOnline = z;
        this.linkOnlineVersion = i8;
        this.poiId = sArr;
        this.floor = sArr2;
        this.stDoorInPos = coord3DDouble2;
        this.stMatchRoadPos = coord3DDouble3;
        this.startDirType = i9;
        this.matchRoadCourse = f8;
        this.requestRouteInfo = str;
        this.compassDir = f9;
        this.gpsDir = f10;
        this.errorDist = f11;
        this.startPosType = i10;
        this.courseAcc = f12;
        this.gpsCoureAcc = f13;
        this.fittingCourse = f14;
        this.fittingCourseAcc = f15;
        this.gpsDatetime = gPSDatetime;
        this.tickTime = bigInteger;
        this.inputTickTime = bigInteger2;
        this.overhead = j4;
        this.matchInfo = arrayList;
        this.matchInfoCnt = j5;
        this.hdop = f16;
        this.roadMatchInfo = arrayList2;
        this.roadMatchInfoCnt = j6;
        this.locInfoChange = z2;
        this.bSnrVoiceBroadcastState = z3;
        this.isAoi = z4;
        this.speedometerIsValid = z5;
        this.speedometer = f17;
        this.isInParking = z6;
        this.parkingFloorNo = b;
        this.parkingLinkType = b2;
        this.buildingId = j7;
    }
}
