package com.xiaopeng.montecarlo.navcore.search;
/* loaded from: classes3.dex */
public class SearchResultCode {
    public static final int G_ERR_BIND_ROAD = 19;
    public static final int G_ERR_CANCEL = 267;
    public static final int G_ERR_ENGINE_NULL = 258;
    public static final int G_ERR_FAILED = -1;
    public static final int G_ERR_GBL_NULL = 260;
    public static final int G_ERR_HMI_NULL = 264;
    public static final int G_ERR_ING = 1;
    public static final int G_ERR_INVALID_PARAM = 2;
    public static final int G_ERR_INVALID_USER = 4;
    public static final int G_ERR_LOGIN_SUCCESS = 268;
    public static final int G_ERR_MEM_NULL = 257;
    public static final int G_ERR_NET_REQ = 20;
    public static final int G_ERR_NOLOGIN = 269;
    public static final int G_ERR_NO_DATA = 3;
    public static final int G_ERR_NO_NET = 6;
    public static final int G_ERR_OK = 0;
    public static final int G_ERR_OUT_OF_RANGE = 13;
    public static final int G_ERR_OUT_SUPPORTSCALE = 5;
    public static final int G_ERR_PARAM_ERROR = 8;
    public static final int G_ERR_PARSE_ERROR = 7;
    public static final int G_ERR_TELEPHONE = 265;
    public static final int G_ERR_TIMEOUT = 266;
    public static final int G_ERR_TOO_FAR = 18;
    public static final int G_ERR_TOO_NEAR = 17;
    public static final int G_REST_ERROR = 518;
    public static final int G_SEARCH_ERRNET_OFFLINE_NODATA = 517;
    public static final int G_SEARCH_OFFLINE_INIT_FAILED = 516;
    public static final int G_SEARCH_OFFLINE_NO_DATA = 515;
    public static final int G_SEARCH_ONLINE_NO_DATA = 513;
    public static final int G_SEARCH_ONLINE_PARSE_ERR = 514;
    public static final int RESULT_EXECUTOR_REJECTED = 1001;
    public static final int RESULT_JSON_PARSE_ERROR = 1003;
    public static final int RESULT_OK = 0;
    public static final int RESULT_REQUEST_INVALID = 1004;
    public static final int RESULT_RESPONSE_ERROR = 1006;
    public static final int RESULT_RESPONSE_FRE_REC_CHARGE_INTERNAL_ERROR = 15010007;
    public static final int RESULT_RESPONSE_FRE_REC_CHARGE_PARAM_USELESS = 15010002;
    public static final int RESULT_RESPONSE_FRE_REC_CHARGE_PARA_ERROR = 15010006;
    public static final int RESULT_RESPONSE_FRE_REC_CHARGE_SUCCESS = 200;
    public static final int RESULT_RESPONSE_FRE_REC_CHARGE_URL_ERROR = 10000002;
    public static final int RESULT_RESPONSE_UNKNOW = 1005;
    public static final int RESULT_USER_CANCELED = 1002;
}
